[build]
  publish = "/"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18.19.1"

[[redirects]]
  from = "/send-email"
  to = "/.netlify/functions/sendEmail"
  status = 200
  method = ["POST"]